title: Arashe
logo: /assets/img/logo.png
description: Light Novel
show_downloads: true
google_analytics: G-7HTQK96HMC
theme: jekyll-theme-minimal
domain: www.arashe.com
url: https://www.arashe.com
baseurl: ""